# Configuration for Game of Death - Infinite Edition

# Frame rate settings
fps = 60

# Grid size (for initial display, grid is actually infinite)
cols = 100
rows = 100

# Random seed (optional)
# seed = 12459

# Audio Engine Selection
# Options: "Spatial" (default) or "DDSP" (neural audio) or "DungeonSynth" or "Hybrid"
audio_engine = "Hybrid"

# Audio Volume (0.0 to 1.0)
audio_volume = 1.0

# Note: 
# - "Spatial" provides immersive 3D audio with individual cell sounds
# - "DDSP" provides real-time neural audio generation based on game state
# - "DungeonSynth" provides a mystical medieval soundscape
# - "Hybrid" combines synthesis, samples, and neural modulation
# Switch this to "Spatial" to use the original spatial audio system

# Game of Life Oracle Configuration

# Graphics and Rendering
render_mode = "colored"     # "colored" | "grayscale" | "cellular" 
use_color_variation = false  # Cells have subtle color variation
use_generation_colors = true  # Color cells by generation number

# Rule Configuration
rule_type = "complex"       # "conway" | "complex" | "highlife"

# Simulation Settings
initial_population = 200    # Number of initial cells
update_interval = 0.1       # Time between generations (seconds)
max_generations = 100000     # Stop after this many generations

# Grid Configuration
grid_size = 200             # Visible grid dimensions
render_distance = 100       # How far to render cells from camera

# UI Configuration
show_ui = true             # Show HUD and statistics
font_size = 16.0           # UI font size

[patterns]
# Built-in patterns that can be loaded
glider = "1:1,2:2,0:3,1:3,2:3"
oscillator = "1:0,1:1,1:2"